### PR TITLE
Fix icons to support HA 110.x

### PR DESCRIPTION
**Pull request by BradleyFord**
Icons have been changed in version 110; so this change updates your code to support.

### CODE REVIEW

**Comment by lorek123** [comment]
@macbury I just checked and it works on my installation

**Comment by CarpeDiemRo** [comment]
@macbury Hello, I have the same problem after an upgrade to 110.x
Here is my PrintScreen.

Screenshot 2020-06-01 at 14 17 50

There is some workaround? I can edit by myself card.js file but I really don't know what to change. Thanks a lot.

**Comment by CarpeDiemRo** [comment]
Sorry, after I logged the bug I observed the new commit. It's working. Thanks a lot.

**Comment by Benouzao** [comment]
Looks like the icon broke again. I'm using HA 113.3.
2020-08-04 22_29_34-Overview - Home Assistant
I confirm I did update the card.js after the latest 11-JUN merge.

**Pull request merged**
